### ISSUE TITLE
Build is failing 

### ISSUE THREAD

**Issue by rahuldeverani** [aws-solutions/centralized-network-inspection-on-aws#13]
**Describe the bug**
Build is failing on "Build the Network Firewall Solution CodeBuild source code" step with the error:

__tests__/network-firewall-manager.spec.ts:281:16 - error TS2571: Object is of type 'unknown'.

281         expect(error["message"]).toBe("Subnet IDs must be in the environment variables")
                   ~~~~~

__tests__/network-firewall-manager.spec.ts:301:20 - error TS2571: Object is of type 'unknown'.

301             expect(error["message"]).toBe("VPC ID must be in the environment variables")
                       ~~~~~

lib/common/firewall-config-validation.ts:14:33 - error TS2307: Cannot find module 'aws-sdk' or its corresponding type declarations.

14 import { NetworkFirewall } from "aws-sdk";
                                   ~~~~~~~~~

lib/common/firewall-config-validation.ts:156:39 - error TS2571: Object is of type 'unknown'.

156             const errorCode: string = error["code"]
                                          ~~~~~

lib/common/firewall-config-validation.ts:161:28 - error TS2571: Object is of type 'unknown'.

161                     error: error["message"]
                               ~~~~~

lib/common/firewall-config-validation.ts:194:39 - error TS2571: Object is of type 'unknown'.

194             const errorCode: string = error["code"]
                                          ~~~~~

lib/common/firewall-config-validation.ts:198:28 - error TS2571: Object is of type 'unknown'.

198                     error: error["message"]
                               ~~~~~

lib/common/send-metrics.ts:13:30 - error TS7016: Could not find a declaration file for module 'uuid'. '/home/ec2-user/environment/test/aws-network-firewall-deployment-automations-for-aws-transit-gateway/source/node_modules/uuid/dist/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/uuid` if it exists or add a new declaration (.d.ts) file containing `declare module 'uuid';`

13 import { v4 as uuidv4 } from "uuid"
                                ~~~~~~

lib/common/send-metrics.ts:14:21 - error TS2307: Cannot find module 'aws-sdk' or its corresponding type declarations.

14 import { SSM } from "aws-sdk"
                       ~~~~~~~~~

lib/common/send-metrics.ts:15:19 - error TS2307: Cannot find module 'axios' or its corresponding type declarations.

15 import axios from "axios"
                     ~~~~~~~

lib/common/send-metrics.ts:48:25 - error TS2571: Object is of type 'unknown'.

48                     if (error["code"] = "ParameterNotFound") {
                           ~~~~~

lib/ec2-manager.ts:14:38 - error TS2307: Cannot find module 'aws-sdk' or its corresponding type declarations.

14 import { EC2, NetworkFirewall } from "aws-sdk"
                                        ~~~~~~~~~

lib/ec2-manager.ts:86:23 - error TS2571: Object is of type 'unknown'.

86       throw new Error(error["message"])
                         ~~~~~

lib/network-firewall-manager.ts:15:33 - error TS2307: Cannot find module 'aws-sdk' or its corresponding type declarations.

15 import { NetworkFirewall } from "aws-sdk"
                                   ~~~~~~~~~

lib/network-firewall-manager.ts:146:23 - error TS2345: Argument of type 'unknown' is not assignable to parameter of type 'string | undefined'.
  Type 'unknown' is not assignable to type 'string'.

146       throw new Error(error)
                          ~~~~~

lib/network-firewall-manager.ts:228:23 - error TS2345: Argument of type 'unknown' is not assignable to parameter of type 'string | undefined'.
  Type 'unknown' is not assignable to type 'string'.

228       throw new Error(error)
                          ~~~~~

lib/network-firewall-manager.ts:327:19 - error TS2345: Argument of type 'unknown' is not assignable to parameter of type 'string | undefined'.
  Type 'unknown' is not assignable to type 'string'.

327       throw Error(error)
                      ~~~~~

lib/service/awsClientConfig.ts:13:36 - error TS2307: Cannot find module 'aws-sdk' or its corresponding type declarations.

13 import {ConfigurationOptions} from 'aws-sdk'
                                      ~~~~~~~~~

lib/service/ec2-service.ts:14:43 - error TS2307: Cannot find module 'aws-sdk' or its corresponding type declarations.

14 import { ConfigurationOptions, EC2 } from 'aws-sdk'
                                             ~~~~~~~~~

lib/service/network-firewall-service.ts:14:55 - error TS2307: Cannot find module 'aws-sdk' or its corresponding type declarations.

14 import { ConfigurationOptions, NetworkFirewall } from 'aws-sdk'
                                                         ~~~~~~~~~

lib/service/network-firewall-service.ts:41:11 - error TS2571: Object is of type 'unknown'.

41       if (e.code === "ResourceNotFoundException") {
             ~

lib/service/network-firewall-service.ts:77:11 - error TS2571: Object is of type 'unknown'.

77       if (error.code === "ResourceNotFoundException") {
             ~~~~~

lib/service/network-firewall-service.ts:94:11 - error TS2571: Object is of type 'unknown'.

94       if (error.code === "ResourceNotFoundException") {
             ~~~~~

lib/service/network-firewall-service.ts:117:13 - error TS2571: Object is of type 'unknown'.

117         if (error.message === "ThrottlingException") {
                ~~~~~

lib/service/network-firewall-service.ts:121:13 - error TS2571: Object is of type 'unknown'.

121         if (error.code === "ResourceNotFoundException") {
                ~~~~~

lib/service/network-firewall-service.ts:159:13 - error TS2571: Object is of type 'unknown'.

159         if (error['message'] === 'Update token is invalid.') {
                ~~~~~

lib/service/network-firewall-service.ts:180:13 - error TS2571: Object is of type 'unknown'.

180         if (error['message'] == 'Update token is invalid.') {
                ~~~~~

lib/service/network-firewall-service.ts:282:72 - error TS7006: Parameter 'ruleGroup' implicitly has an 'any' type.

282         response.FirewallPolicy?.StatefulRuleGroupReferences?.forEach((ruleGroup) => {
                                                                           ~~~~~~~~~

lib/service/network-firewall-service.ts:285:73 - error TS7006: Parameter 'ruleGroup' implicitly has an 'any' type.

285         response.FirewallPolicy?.StatelessRuleGroupReferences?.forEach((ruleGroup) => {
                                                                            ~~~~~~~~~

Found 29 errors.

If I use Node version 15 , I face this error during "Build the CDK code" step:
> network-firewall-automation-solution@1.0.0 build
> tsc

test/network-firewall-automation-solution.test.ts:37:40 - error TS2345: Argument of type 'import("C:/Users/TABSBE/OneDrive - RWWA/github/aws-network-firewall-deployment-automations-for-aws-transit-gateway/source/node_modules/@aws-cdk/core/lib/stack").Stack' is not assignable to parameter of type 'import("C:/Users/TABSBE/OneDrive - RWWA/github/aws-network-firewall-deployment-automations-for-aws-transit-gateway/source/node_modules/@aws-cdk/assert/node_modules/@aws-cdk/core/lib/stack").Stack'.
  Type 'Stack' is missing the following properties from type 'Stack': reportMissingContextKey, splitArn, exportValue, maxResources

37     expect(SynthUtils.toCloudFormation(getTestStack())).toMatchSnapshot();

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Please complete the following information about the solution:**
Versions:
CDK: 1.77.0
NODE: v14.1.0
NPM: 6.14.4

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**

**Comment by gockle** [comment]
Hi @rahuldeverani 
Can you try running the following commands to build the module,

```
cd source/networkfirewallAutomations
npm install
npm run build
```

**Comment by rahuldeverani** [comment]
Sorry for replying late , it worked!
